const actionTypes = {
  LOGGED_IN: 'LOGGED_IN',
  FETCH_USER: 'FETCH_USER',
  PROFILE_IMAGE: 'PROFILE_IMAGE',
  NO_PROFILE_IMAGE: 'NO_PROFILE_IMAGE',
  NO_TEMPLATE: 'NO_TEMPLATE',
  FETCH_WORKOUT: 'FETCH_WORKOUT'
};

export default actionTypes;
